### ISSUE TITLE
Discuss: move plugin to the Perl5-Alien organisation

### ISSUE THREAD

**Issue by zmughal** [Getty/p5-dist-zilla-plugin-alien#10]
@Getty, do you mind if this plugin is transferred to the @Perl5-Alien GitHub org?

@plicease has been doing much of the recent work with improving Alien-Base and having it under the umbrella of the organisation will make it easier to keep the plugin up to date with the latest changes.

It would also be great if @plicease (and possibly the other contributors to Alien-Base) could have comaint on the plugin.

**Comment by plicease** [comment]
The other AB devs are cpan JBERGER (@jberger) and cpan ETJ (@mohawk2)

**Comment by jberger** [comment]
If it helps anything, @Getty might remember that I'm not a dzil fan, but I know that @zmughal is at least. With him in the Perl5-Alien org, I know that someone will be on the pulse of what the plugin needs.

**Comment by Getty** [comment]
Yeah, primary important for me is what the Dzil Community needs to fully enjoy the module, so if we discuss plans done on the module i have no problem shifting it over to the other github. In other words: if it breaks my pluginbundle, i get mad ;-) I will come back to this the next days, i dont think we are in hurry

**Comment by jberger** [comment]
@Getty no hurry and understood :smile:

**Comment by Getty** [comment]
I can btw transfer this only over if i am admin in the perl5-alien org

**Comment by zmughal** [comment]
If you want, you can transfer it to me and then I'll move it to @Perl5-Alien.

We'll take good care of it! Both @plicease and I are using the plugin and we wouldn't want to make more work for ourselves. :-)

Again, no hurry.

**Comment by zmughal** [comment]
Hi @Getty, just checking in re: this issue!

**Comment by plicease** [comment]
@Getty can we move forward with this?  I can make sure that you have access to this repo once it is put into the @Perl5-Alien org.  I think the best way to move forward is to do as @zmughal suggests and transfer it to him so that he can transfer it to the org.

**Comment by Getty** [comment]
So it stays that the only option is that I lose any administrative power over the repository without any reason? I am confused why no one references to my request on that. I just don't want to ask someone for things I normally was able to do (like adding contributors). I don't see any specific reason why I should give that up. Especially when I want to be clear that it is for me relevant that it works in the supposed way and I don't like to get the feeling I don't have the control anymore. The attitude here is not very convincing.

**Comment by plicease** [comment]
I am sorry, I didn't mean to offend you.  Access and Admin for the plugin for @getty is always what I intended, and if I seemed to indicate otherwise I apologize.

**Comment by Getty** [comment]
Yeah, it wasn't really obvious ;) now its more easy!

**Comment by Getty** [comment]
I still can't move over tho, whats the big deal about giving me admin rights? anyway just owners there ;)

**Comment by Getty** [comment]
Transfering to @zmughal now tho.....

**Comment by zmughal** [comment]
Thanks @Getty. I have made the transfer to @Perl5-Alien. :-)

**Comment by Getty** [comment]
Well I still can't add contributors tho....... Do we really have to make the stupid dance or can't you just add the admin rights and i am happy? Seriously, this gets annoying

**Comment by plicease** [comment]
@Getty you should be able to add collaborators.  If you are unable to please let me know and I will do what I can do resolve the situation.
